#!/bin/bash

data_dir="refine_census"
name="box"

if [ ! -d "$data_dir" ]; then
    mkdir "$data_dir"
fi

if [[ $# > 0 ]]; then
    box="$1"
fi

if [[ $# > 1 ]]; then
    name="$1"
    box="$2"
fi

echo '1' | ./refine --fillHoles --box "$box" --maxDepth 96 --truncateDepth 6 --inventDepth 6 --maxSize 30000000 --words words --ballSearchDepth -1 --maxArea 5.2 --powers powers_combined --mom /dev/null --parameterized /dev/null > "$data_dir/$name.out" 2> "$data_dir/$name.err"
