#!/bin/bash

data_dir="refine_census"
name="box"
maxArea="5.75"
minArea="0.0"

if [ ! -d "$data_dir" ]; then
    mkdir "$data_dir"
fi

if [[ $# > 0 ]]; then
    box="$1"
fi

if [[ $# > 1 ]]; then
    name="$1"
    box="$2"
fi

if [[ $# > 2 ]]; then
    name="$1"
    maxArea="$2"
    box="$3"
fi

echo '1' | ../bin/refine_slopes --fillHoles --box "$box" --maxDepth 330 --truncateDepth 6 --inventDepth 70 --maxSize 3000000 --words ../words --ballSearchDepth 6 --minArea "$minArea" --maxArea "$maxArea" --powers ../powers_combined --mom /dev/null --parameterized /dev/null > "$data_dir/$name.out" 2> "$data_dir/$name.err"
