#!/bin/bash

data_dir="refine_census"
name="box"
area="5.24"

if [ ! -d "$data_dir" ]; then
    mkdir "$data_dir"
fi

if [[ $# > 0 ]]; then
    box="$1"
fi

if [[ $# > 1 ]]; then
    name="$1"
    box="$2"
fi

if [[ $# > 2 ]]; then
    name="$1"
    area="$2"
    box="$3"
fi

echo '1' | ./bin/refine --fillHoles --box "$box" --maxDepth 36 --truncateDepth 6 --inventDepth 12 --maxSize 3000000 --words words_debug --ballSearchDepth 9 --maxArea "$area" --powers powers_combined --mom /dev/null --parameterized /dev/null > "$data_dir/$name.out" 2> "$data_dir/$name.err"
