#!/bin/bash

data_dir="refine_census"
name="box"
maxArea="6.02"
minArea="0.0"
words_file="../words_mt_new"
#words_file=""

if [ ! -d "$data_dir" ]; then
    mkdir "$data_dir"
fi

if [[ $# > 0 ]]; then
    box="$1"
fi

if [[ $# > 1 ]]; then
    name="$1"
    box="$2"
fi

if [[ $# > 2 ]]; then
    name="$1"
    maxArea="$2"
    box="$3"
fi

echo '1' | ../bin/refine_slopes_mt --fillHoles --box "$box" --maxDepth 330 --truncateDepth 6 --inventDepth 24 --maxSize 1000000 --words "$words_file" --e2words ../e2_words --ballSearchDepth 6 --minArea "$minArea" --maxArea "$maxArea" --powers ../powers_combined > "$data_dir/$name.out" 2> "$data_dir/$name.err"
