#!/bin/bash

data_dir="refine_census"
name="box"
area="6.0"

if [ ! -d "$data_dir" ]; then
    mkdir "$data_dir"
fi

if [[ $# > 0 ]]; then
    box="$1"
fi

if [[ $# > 1 ]]; then
    name="$1"
    box="$2"
fi

if [[ $# > 2 ]]; then
    name="$1"
    area="$2"
    box="$3"
fi

echo '1' | ./refine --fillHoles --box "$box" --maxDepth 96 --truncateDepth 96 --inventDepth 10 --maxSize 30000000 --words words --ballSearchDepth -1 --maxArea "$area" --powers powers_combined --mom /dev/null --parameterized /dev/null > "$data_dir/$name.out" 2> "$data_dir/$name.err"
